#!/bin/bash

ans="$1"
export ans
case $ans in
        "create")
               cat << EOF > commands/create.py
#!/usr/bin/python3 -tt
import subprocess
import os
import shutil
import content

title = "$2"
name = str("index.html")
bcx = "$2"
stylevar = "$3"

if stylevar == "":
	stylevar = "example.css"

sFile = "styles/"+ stylevar
os.mkdir(bcx)
tFile = bcx + '/'+ 'style.css'
fileHandle = open(sFile, "r")
texts = fileHandle.readlines()
fileHandle.close()
fileHandle = open(tFile, "w")
for s in texts:
    fileHandle.write(s)
fileHandle.close()
print(stylevar +" style added")

path = bcx +'/'+ name
bcontent = content.example()
hcontent = str("\t<title>"+title+"</title>") + content.head()
head = str("<head>\n" + hcontent + "\n</head>\n")
#componet = example()
body = str("<body>\n"+bcontent+"\n</body>")
file = open(path, "w")
file.write("<!DOCTYPE HTML>" + os.linesep)
file.write(head)
file.write(body)
file.close()
EOF
chmod 770 commands/create.py

./commands/create.py

exit 0
mv $2 folder
                ;;
        "help")
                echo "Anura usage:"
		echo "anura <command> <arguments>"
		echo "create <name> <style>"
                ;;
	"rename")
		mv $2 $3
		;;
	"delete")
		rm -rf $2
		;;
esac

